[package]
name = "hue-arc"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lab = "0.9"
luv = "0.9"
srgb = "0.1.4"
webp = "0.2.6"
hsl = "0.1"
